### ISSUE TITLE
Docs for RHEL / CentOS should also mention they apply for Fedora

### ISSUE THREAD

**Issue by RafalSkolasinski** [k3s-io/docs#119]
This note [here](https://docs.k3s.io/advanced#red-hat-enterprise-linux--centos) on `firewalld` should also mention that this apply to Fedora as well. It will be easier find-able if one use search and put in `Fedora`.

**Comment by dereknola** [comment]
We could reword it as "Fedora and OpenSUSE Based Distros" which covers most distros that use firewalld, but I'm not sure if vagueness is better. Additionally, UFW is on "Debian Based Distros" not just Ubuntu.
