### ISSUE TITLE
Document flag deprecation policy

### ISSUE THREAD

**Issue by cwayne18** [k3s-io/docs#127]
We wrote up a deprecation policy (defined here: https://github.com/k3s-io/k3s/blob/master/docs/adrs/deprecating-and-removing-flags.md) that's been discussed and agreed upon within the team -- let's write up a page on the docs and make sure it's publicly stated.

**Comment by bhavyastar** [comment]
Hey @cwayne18 , I would like to work on this issue.

**Comment by dereknola** [comment]
@bhavyastar are you still working on this issue?
