### ISSUE TITLE
English Errors in Rancher products K3s page

### ISSUE THREAD

**Issue by susesgartner** [k3s-io/docs#147]
Page: https://www.rancher.com/products/k3s

There are 2 errors on this page:
1. In the text block under "Why K3s and Rancher?->A CNCF Sandbox Project" the description for this is missing the word "to", it should read: 
"K3s was originally a Rancher project. In June 2020 Rancher donated K3s **to** the CNCF as a testament to the Rancher's commitment to the open source community"

2. In the text block under "Why K3s and Rancher?->Perfect for Edge" the word "available" is misspelled "avalible".

<img width="1148" alt="image" src="https://github.com/k3s-io/docs/assets/136753565/53da4cfd-0022-4b1a-91e5-95ea789b254c">

**Comment by dereknola** [comment]
Errors have now been resolved
