### ISSUE TITLE
The kubernetes-dashboard cannot be installed through the document

### ISSUE THREAD

**Issue by ckfear** [k3s-io/docs#155]
https://docs.k3s.io/installation/kube-dashboard#deploying-the-kubernetes-dashboard
The dashboard of k8s has released the latest version `v3.0.0-alpha0`, and the installation method has been updated. Using the current document method to install will prompt a 404 error.Maybe you should limit the installation to a specific version instead of getting it from the github release page.

**Comment by brandond** [comment]
Honestly I'd probably just drop the dashboard from the docs entirely; I don't really see it being used much these days, as there are better tools available for visualizing cluster resources.

**Comment by nicklimmm** [comment]
Just a thought, should we at least pin the version to `v2.7.0` in the guide? 

At least users won't get errors when running the commands
