### ISSUE TITLE
[K3s] add --audit-policy-file parameter in hardening guide

### ISSUE THREAD

**Issue by davinkevin** [k3s-io/docs#18]
**Request Summary:**

In current hardening guide example, we don't have any `--audit-policy-file` parameter defined in the `k3s server` command example.

**Details:**

If we don't provide any `--audit-policy-file`, the audit logging is disabled ([default behaviour of k8s](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy)). 

Having some kind of "default" `audit.k8s.io/v1:Policy`  file and the parameter in the command example could be a better description of "how to enable it", especially when we enable every other parameters about `audit-log`.

Thank you

BTW, if you provide me some information about what we should do on this one, I would be able to do a PR. 

NOTE: Creation requested by @jtravee in this [comment](https://github.com/rancher/docs/issues/3656#issuecomment-1227480242), as a clone of https://github.com/rancher/docs/issues/3656

**Comment by dereknola** [comment]
We have a whole section describing how to use the K8s apiserver `audit-policy-file` https://k3s-io.github.io/docs/docs/security/hardening-guide#api-server-audit-configuration
