### ISSUE TITLE
air-gap installation instruction to include steps for installing k3s-selinux packages offline

### ISSUE THREAD

**Issue by cwrx777** [k3s-io/docs#190]
For [air-gap installation](https://docs.k3s.io/installation/airgap), provide instructions on how to download and install container-selinux and k3-selinux package manually/offline. 

```
[INFO]  Skipping k3s download and verify
[INFO]  Skipping installation of SELinux RPM
[ERROR]  Failed to find the k3s-selinux policy, please install:
    dnf install -y container-selinux
    dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/8/noarch/
```

**Comment by dereknola** [comment]
This is already mentioned in https://docs.k3s.io/advanced?_highlight=seli#selinux-support, but we should link back to that section in the Airgap page.
