### ISSUE TITLE
Confusing documentation on secrets encryption.

### ISSUE THREAD

**Issue by werdnum** [k3s-io/docs#198]
I can't quite figure out this page:

https://docs.k3s.io/cli/secrets-encrypt

I'm trying to figure out how to enable secrets encryption on my cluster. I didn't do anything special to turn it on, so I presume it is off.

Under 'Encryption key rotation', it says "Starting K3s without encryption and enabling it at a later time is currently not supported." Does this mean that it is impossible to enable secrets encryption on a cluster that didn't have it on from the start? Or does it mean that you have to restart the `k3s` server in order to enable secrets encryption?

There is also a section called "Secrets Encryption Disable/Enable" - but this seems to presuppose that the `--secrets-encrypt` flag is already set, I've disabled secrets encryption and I now want to re-enable it.

**Comment by brandond** [comment]
> Starting K3s without encryption and enabling it at a later time is currently not supported.

You can't add the flag after the cluster has been started.

> I've disabled secrets encryption and I now want to re-enable it.

What steps did you follow to disable it?

**Comment by dereknola** [comment]
The section on Disable clearly states:
```
After launching a server with `--secrets-encryption` flag, secrets encryption can be disabled.
```
Only if you start a server with `--secrets-encryption` the first time can you disable/reenable it.
