### ISSUE TITLE
[Translation]  K3s Docs Into Arabic.

### ISSUE THREAD

**Issue by AbdelatifAitBara** [k3s-io/docs#270]
Hi,

I would like to start translating the docs of K3s into Arabic, to allow Arabic speakers to understand better this project.

Best regards.

**Comment by dereknola** [comment]
You are welcome to open PRs for Arabic translations. Note that we will not be able to maintain those translations. The same is true of the current zh and kr translations. We don't have native speakers on the project, so it will essentially be a "snapshot" of the docs at time of translation. Of course you are free to continue open regular translation update PR as you see fit as well.

**Comment by AbdelatifAitBara** [comment]
@dereknola Thank you, 
I'll try to start the translations now as a small project, and maybe with time we'll have other contributors to help us to maintain it as mush as possible.

**Comment by dereknola** [comment]
Closing issue as stale
