### ISSUE TITLE
Release notes are 2 months out of date: PR bot broken?

### ISSUE THREAD

**Issue by corneliusroemer** [k3s-io/docs#281]
The release notes on the docs page are about 2 months out of date vs actual releases

For example it's missing 1.30 entirely: https://github.com/k3s-io/docs/tree/main/docs/release-notes

https://docs.k3s.io/release-notes/v1.29.X

A bot used to make PRs, maybe it's broken?

See last PR: https://github.com/k3s-io/docs/pull/249

**Comment by brandond** [comment]
We don't have a bot for it yet, just @dereknola

**Comment by dereknola** [comment]
https://github.com/k3s-io/docs/pull/282
