### ISSUE TITLE
Ubuntu 22.04 has nftables enabled by default

### ISSUE THREAD

**Issue by drpump** [k3s-io/docs#30]
I’ve just set up a new machine with the latest, stable Ubuntu 22.04. This release has nftables enabled by default, so requires the same fix as Raspberry Pi OS to revert to legacy iptables. I would suggest updating the requirements page to reflect this and perhaps updating the known issues section. 

Note that this issue surfaced when trying to define Ingress resources to access a simple HTTP service (whoami) on a default k3s installation (i.e. as per the quick start instructions). Matching requests to the public traefik ports (80 & 443) were failing with a 504 timeout error because it couldn’t route the network traffic, even though the service was accessible via the private k3s network address associated with the service. Enabling traefik debug didn’t shed any light on the problem, and I spent lots of hours trying to track down the issue.

I’ve attached a file containing deployment, service and ingress definitions to reproduce, assuming `whoami` is added to `/etc/hosts` as an alternative hostname for the machine. 
[whoami.txt](https://github.com/k3s-io/docs/files/9702570/whoami.txt)

**Comment by brandond** [comment]
You shouldn't have to revert to nftables. It's been supported for quite a while. What problems are you having with it?

**Comment by drpump** [comment]
Traefik attempted to route the requests but everything just timed out. Reverting to legacy iptables fixed it immediately.
