### ISSUE TITLE
[k3s/v1.29] - Cannot find etcd config as stated in hardening guide

### ISSUE THREAD

**Issue by cwrx777** [k3s-io/docs#300]
release:  [1.29.4](https://docs.k3s.io/release-notes/v1.29.X#release-v1294k3s1)
I am unable to find etcd config as stated [here](https://docs.k3s.io/security/self-assessment-1.8#21-ensure-that-the---cert-file-and---key-file-arguments-are-set-as-appropriate-automated)

**Comment by brandond** [comment]
Are you sure you're using etcd at all? By default, k3s uses sqlite.

**Comment by cwrx777** [comment]
The etcd config is created after using `--cluster-init`

**Comment by cwrx777** [comment]
The etcd config is created after using `--cluster-init`
