### ISSUE TITLE
Release Notes table missing ServiceLB (klipper-lb) column

### ISSUE THREAD

**Issue by migs35323** [k3s-io/docs#325]
As klipper-lb (now i believe it was renamed to service lb) is a component included with k3s (same with others like traefik and local path),
I believe the versions that k3s ships with should be included in the releases table.

examples:
https://docs.k3s.io/release-notes/v1.30.X
https://docs.k3s.io/release-notes/v1.28.X

and as a thank you note for the maintainers, this releases tables are very usefull!
when i upgrade my k3s i like to check this table to see what components change and a hint where can i look for issues <3

**Comment by brandond** [comment]
What version would we even show? There is no separate versioning for ServiceLB. It exists within the K3s codebase as part of our stub cloud controller. 

https://github.com/k3s-io/k3s/blob/master/pkg/cloudprovider/servicelb.go
