### ISSUE TITLE
Path to cmdline.txt file has been changed in Raspberry Pi OS

### ISSUE THREAD

**Issue by votdev** [k3s-io/docs#333]
At https://docs.k3s.io/installation/requirements?os=pi there is a guide how to enable cgroups on Raspberry Pi OS. All other howtos i found are mentioning `/boot/firmware/cmdline.txt` instead of `/boot/cmdline.txt`. This needs to be validated. Sadly i have no Raspi hardware to do that myself.

Maybe this applies only to the latest Raspberry Pi OS (Bookworm).

References:
- https://everythingdevops.dev/step-by-step-guide-creating-a-kubernetes-cluster-on-raspberry-pi-5-with-k3s/
- https://medium.com/@stevenhoang/step-by-step-guide-installing-k3s-on-a-raspberry-pi-4-cluster-8c12243800b9
- https://ionutbanu.medium.com/kubernetes-on-raspberry-pi-5-part-3-install-k3s-on-master-node-f95ea35a8b1c
- https://github.com/k3s-io/k3s/issues/2067#issuecomment-801710748

**Comment by dereknola** [comment]
RaspberryPi OS when it moved to Debian 12 base got rid of the migration symlink between the old `/boot/cmdline.txt` and the new `/boot/firmware/cmdline.txt`

**Comment by dereknola** [comment]
Addressed with https://github.com/k3s-io/docs/pull/338
