### ISSUE TITLE
Add "why the name kiss 'k3s'" to FAQ? 

### ISSUE THREAD

**Issue by motevets** [k3s-io/docs#34]
I was chatting with someone last night about k3s, and I said, "well I'm pretty sure k3s is a shortening of KISS (keep it simple,)" and they said, "wouldn't that be k2s?" This made me wonder, why is it called "k3s", and I couldn't find any information about it on the website or documentation. Would you consider adding it to the FAQ?

Thanks!

**Comment by brandond** [comment]
https://github.com/k3s-io/k3s/blob/master/README.md#whats-with-the-name
