### ISSUE TITLE
Certificate Rotation in Advanced Options ?

### ISSUE THREAD

**Issue by udf2457** [k3s-io/docs#42]
Is there any reason why Certificate Rotation is [hidden away under Advanced Options ](https://docs.k3s.io/advanced#certificate-rotation)?

Surely its a fairly critical bit of sysadmin and not an advanced option ? Maybe it could go under "Installation" instead ?

Also, perhaps a bit of clarity on what breaks if the certificates go unrotated would not go amiss ?  Equally I'm unclear why k3s needs a hard reboot and not a reload (_SIGHUP_) ?

**Comment by dereknola** [comment]
The reasons it is under advanced is simple: K3s does all the work for you when it comes to Certificate Rotation. As long as you restart or upgrade K3s once-a-year (which you should be doing to receive patch releases at a minimum) the certificates are dealt with. 

As for why K3s needs a hard reboot, the core Kubernetes components (controller-manager, apiserver, scheduler) are all contained within a single K3s server process. There isn't a independent apiserver process we can just restart.

**Comment by udf2457** [comment]
@dereknola Ah ok, thanks for the clear explanation. I assume this also covers the newly supported embedded `etcd` in terms of certs ?

Slightly off-topic: Honestly, I'm really loving k3s. I mostly avoided Kubernetes until now becuase the "original" k8s is such a monster to manage.  But the more I dig into k3s the more I find its just that right sweet spot - only thing I'm unsure about is whether I'll have to use `envoy` instead of the out-of-the-box `traefik` because as I understand it, `traefik` does not (yet?) play well with `spiffe/spire` (https://github.com/traefik/traefik/issues/9376).

**Comment by dereknola** [comment]
To your question: yes, the embedded etcd works the same way, certs are auto rotated regardless of which backend DB you use. 

Always glad that K3s is working well :) I'm not really up on my Traefik issues, so I can't really comment on that. Feel free to mess around with `--disable traefik`. 

The stance of the K3s team is clear: we stand by our "opininated" component decisions, we aren't getting rid of Traefik or CoreDNS or the other bundled components anytime soon. But we always want it to be easy for users to branch out and disable anything they don't like.
