### ISSUE TITLE
Incorrect file name listing k3s images

### ISSUE THREAD

**Issue by Tom-GK** [k3s-io/docs#69]
In "docs/installation/private-registry.md" in the section "Adding Images to the Private Registry" it says to:
 "obtain the **k3s-images.txt** file from GitHub", but that file does not seem to exist. 

However, a file "scripts/airgap/**image-list.txt**" does exist.

Perhaps that is the intended file?

**Comment by brandond** [comment]
It specifically says `obtain the k3s-images.txt file from GitHub for the release you are working with.` It sounds like you're looking at the git repo contents, not the release as instructed? See the artifact list at https://github.com/k3s-io/k3s/releases/tag/v1.26.0%2Bk3s1: https://github.com/k3s-io/k3s/releases/download/v1.25.4%2Bk3s1/k3s-images.txt

**Comment by Tom-GK** [comment]
Sorry Brandon, my mistake. 
Thanks for the pointer in the right direction!
